apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../base
patchesStrategicMerge:
- deployment.yaml
replicas:
- count: 3
  name: vote
images:
- name: docker.io/schoolofdevops/vote
  newTag: v4
namespace: instavote
commonAnnotations:
  supported-by: yourmom
configMapGenerator:
- envs:
  - options.env
  name: vote-options
labels:
- includeSelectors: true
  pairs:
    env: dev
    project: instavote
