apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- db-staging-helmrelease.yaml
- instavote-gitrepository.yaml
- instavote-helmrepository.yaml
- redis-staging-kustomization.yaml
- result-staging-helmrelease.yaml
- vote-staging-kustomization.yaml
- worker-staging-kustomization.yaml
