---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: redis-dev
  namespace: flux-system
spec:
  healthChecks:
  - kind: Deployment
    name: redis
    namespace: instavote
  interval: 30s
  path: ./deploy/redis/dev
  prune: true
  sourceRef:
    kind: GitRepository
    name: instavote
  targetNamespace: instavote
  timeout: 2m0s
