apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../base
namespace: instavote
commonAnnotations:
  supported-by: yourmom
labels:
- includeSelectors: true
  pairs:
    env: dev
    project: instavote
