---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: vote
  namespace: instavote
  labels:
    app: vote
  annotations:
    ingress.cilium.io/force-https: disabled
spec:
  ingressClassName: cilium
  rules:
  - host: vote.pi.turbo.internal
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: vote
            port:
              number: 80
